import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarPage from "./navbar/page";
import HeroPage from "@/Components/Hero";
import CollectionOfThings from "@/Components/CollectionOfThings";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col w-11/12 mt-3 mx-auto">
        <section>
          <NavBarPage></NavBarPage>
          <HeroPage></HeroPage>
          <CollectionOfThings></CollectionOfThings>
        </section>
        
        <main>
          {children}
        </main>

        <section>
          <Footer></Footer>
        </section>

      </body>
    </html>
  );
}
